connectionString: mongodb://stressmongodb:g4ENygXG5F070wWtC1coNHwPFuxXnFObr3HGY2gOzZwpz3O2qjdKBMc4njfq5U12hrQsOIEHemkImQ6ymHGSjA==@stressmongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@stressmongodb@
databaseName: stress_management_app

